# Generated by Django 5.1 on 2024-09-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatihan',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
