# Generated by Django 5.1 on 2024-09-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_remove_akun_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
